-- data/schema.sql — canonical APIx fare-quote schema (SIH26056)
--
-- THE ONE SCHEMA. Every fare quote in this project lands in `fare_quotes`,
-- whether it came from the simulator or from a real scrape. Downstream code
-- (ETL, index math, API, dashboard) never needs to know which produced a row
-- -- it reads the `source` column if it cares, and otherwise treats all rows
-- identically. See CLAUDE.md "Repo conventions".
--
-- This script is idempotent: safe to run against an existing DB.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;


-- ---------------------------------------------------------------------------
-- schema_version — so a later phase can tell what shape the DB is in
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_version (
    version     INTEGER NOT NULL,
    applied_at  TEXT    NOT NULL,
    note        TEXT
);


-- ---------------------------------------------------------------------------
-- fare_quotes — one row per (source, airline, route, travel_date, query_date,
-- booking_class) observation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fare_quotes (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Provenance. This is the simulated-vs-real distinction that CLAUDE.md
    -- ground rule 5 requires be visible everywhere; it starts here.
    --   'simulated'          -- generated by scraper/simulator.py
    --   'live'               -- genuinely scraped from a real site
    --   'fallback_simulated' -- a live scrape was attempted and failed, so the
    --                           simulator answered instead. NOT a real quote.
    source                  TEXT NOT NULL
                            CHECK (source IN ('simulated', 'live', 'fallback_simulated')),

    airline                 TEXT NOT NULL,          -- IATA code, e.g. '6E' (see config/airlines.yaml)
    origin                  TEXT NOT NULL,          -- IATA airport code, e.g. 'DEL'
    dest                    TEXT NOT NULL,          -- IATA airport code, e.g. 'BOM'

    travel_date             TEXT NOT NULL,          -- ISO 'YYYY-MM-DD': date of the flight
    query_date              TEXT NOT NULL,          -- ISO 'YYYY-MM-DD': date the fare was observed
    advance_purchase_days   INTEGER NOT NULL        -- travel_date - query_date, in days
                            CHECK (advance_purchase_days >= 0),

    -- Fares in `currency` units. NULL is legal when is_available = 0
    -- (sold out / no fare returned) -- Phase 4 flags rather than drops these.
    base_fare               REAL CHECK (base_fare  IS NULL OR base_fare  >= 0),
    taxes                   REAL CHECK (taxes      IS NULL OR taxes      >= 0),
    total_fare              REAL CHECK (total_fare IS NULL OR total_fare >= 0),
    currency                TEXT NOT NULL DEFAULT 'INR',

    booking_class           TEXT NOT NULL DEFAULT 'ECONOMY',
    is_available            INTEGER NOT NULL DEFAULT 1
                            CHECK (is_available IN (0, 1)),

    scraped_at              TEXT NOT NULL,          -- ISO 8601 timestamp of observation

    -- NOTE: deliberately NOT enforcing total_fare = base_fare + taxes here.
    -- Phase 4's ETL is specified to *validate and flag* that mismatch, which it
    -- cannot do if the DB refuses the row on insert. Real scraped data breaks
    -- this identity often (surcharges, rounding); silently rejecting it would
    -- hide a genuine data-quality signal.

    UNIQUE (source, airline, origin, dest, travel_date, query_date, booking_class)
);

-- Index-construction and dashboard read patterns: by route, by observation
-- date, by source, by carrier.
CREATE INDEX IF NOT EXISTS idx_fq_route        ON fare_quotes (origin, dest, travel_date);
CREATE INDEX IF NOT EXISTS idx_fq_query_date   ON fare_quotes (query_date);
CREATE INDEX IF NOT EXISTS idx_fq_source       ON fare_quotes (source);
CREATE INDEX IF NOT EXISTS idx_fq_airline      ON fare_quotes (airline);
CREATE INDEX IF NOT EXISTS idx_fq_apd          ON fare_quotes (advance_purchase_days);
